/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekbaru;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author jono
 */
public class kakulator extends javax.swing.JFrame {

    /**
     * Creates new form kakulator
     */
    public kakulator() {
        initComponents();
        hapus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKedua = new javax.swing.JTextField();
        txtPertama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        btnbagi = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnmodulus = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btnceklis = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("masukan nilai :");

        jLabel2.setText("masukan nilai  :");

        txtKedua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeduaActionPerformed(evt);
            }
        });
        txtKedua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeduaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeduaKeyTyped(evt);
            }
        });

        txtPertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPertamaActionPerformed(evt);
            }
        });
        txtPertama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPertamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPertamaKeyTyped(evt);
            }
        });

        jLabel3.setText("Hasil  :");

        txtHasil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHasilKeyPressed(evt);
            }
        });

        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnkurang.setText("-");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btnkali.setText("x");
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });

        btnbagi.setText("/");
        btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbagiActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnmodulus.setText("%");
        btnmodulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodulusActionPerformed(evt);
            }
        });
        btnmodulus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnmodulusKeyPressed(evt);
            }
        });

        btnx2.setText("X2");
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });

        btnceklis.setText("√");
        btnceklis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceklisActionPerformed(evt);
            }
        });

        jLabel4.setText("KALKULATOR SEDERHANA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPertama, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtKedua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmodulus, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnx2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnbagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnkali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnceklis, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntambah)
                            .addComponent(btnkali))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtKedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnkurang)
                                    .addComponent(btnbagi))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnx2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(btnmodulus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnceklis))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPertamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPertamaActionPerformed

    private void txtKeduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeduaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtKeduaActionPerformed

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaliActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(txtPertama.getText());
        int bil2 = Integer.parseInt(txtKedua.getText());
        perkalian(bil1, bil2);
    }//GEN-LAST:event_btnkaliActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(txtPertama.getText());
        int bil2 = Integer.parseInt(txtKedua.getText());
        penjumlahan(bil1, bil2);
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(txtPertama.getText());
        int bil2 = Integer.parseInt(txtKedua.getText());
        pengurangan(bil1, bil2);
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbagiActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(txtPertama.getText());
        int bil2 = Integer.parseInt(txtKedua.getText());
        pembagian(bil1, bil2);
    }//GEN-LAST:event_btnbagiActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
   txtHasil.setText("");
        txtPertama.setText("");
        txtKedua.setText("");
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txtKeduaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeduaKeyPressed
        btntambah.setEnabled(true);
        btnkurang.setEnabled(true);
        btnkali.setEnabled(true);
        btnbagi.setEnabled(true);
        btnmodulus.setEnabled(true);
        btnx2.setEnabled(true);
        btnceklis.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeduaKeyPressed

    private void txtPertamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPertamaKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtPertamaKeyPressed

    private void txtHasilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHasilKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasilKeyPressed

    private void btnmodulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodulusActionPerformed
        // TODO add your handling code here:
            int bil1 = Integer.parseInt(txtPertama.getText());
        int bil2 = Integer.parseInt(txtKedua.getText());
        modulus(bil1, bil2);
    }//GEN-LAST:event_btnmodulusActionPerformed

    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(txtPertama.getText());
        int bil2 = Integer.parseInt(txtKedua.getText());
        pangkat (bil1, bil2);
    }//GEN-LAST:event_btnx2ActionPerformed

    private void txtPertamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPertamaKeyTyped
       
     char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
                )
            )
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtPertamaKeyTyped

    private void txtKeduaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeduaKeyTyped
        // TODO add your handling code here:
     char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
                )
            )
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtKeduaKeyTyped

    private void btnmodulusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnmodulusKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnmodulusKeyPressed

    private void btnceklisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceklisActionPerformed
        // TODO add your handling code here:
        int bil = Integer.parseInt(txtPertama.getText());
        akar (bil);
    }//GEN-LAST:event_btnceklisActionPerformed
    public void hapus() {
        txtHasil.setEnabled(false);
        txtHasil.setText("");
        txtPertama.setText("");
        txtKedua.setText("");
        btntambah.setEnabled(false);
        btnkurang.setEnabled(false);
        btnkali.setEnabled(false);
        btnbagi.setEnabled(false);
        btnmodulus.setEnabled(false);
        btnx2.setEnabled(false);
        btnceklis.setEnabled(false);
        
    }

    public void penjumlahan(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 + bilangan2;
        txtHasil.setText(hasil + "");
    }

    public void pengurangan(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 - bilangan2;
        txtHasil.setText(hasil + "");
    }

    public void perkalian(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 * bilangan2;
        txtHasil.setText(hasil + "");
    }

    public void pembagian(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 / bilangan2;
        txtHasil.setText(hasil + "");
    }
    public void modulus(int bilangan1, int bilangan2) {
        int hasil = 0;
        hasil = bilangan1 % bilangan2;
        txtHasil.setText(hasil + "");
    }
      public void pangkat(int bilangan1, int bilangan2) {
        double hasil = 0;
        hasil = math.pow(bilangan1, bilangan2);
        txtHasil.setText(hasil + "");
    }
          public void akar(int bilangan1) {
        double hasil = 0;
        hasil = math.sqrt(bilangan1);
        txtHasil.setText(hasil + "");
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kakulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kakulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kakulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kakulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kakulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbagi;
    private javax.swing.JButton btnceklis;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnmodulus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtKedua;
    private javax.swing.JTextField txtPertama;
    // End of variables declaration//GEN-END:variables
}
